GP-1571
oicr-gsi/ESTIMATE pull request #1
Opened 2018-05-16 15:51 UTC by prisnir

2018-05-29 15:45 UTC, prisnir commented
retest this please

2018-06-11 14:18 UTC, prisnir commented
retest this please

2018-06-12 22:01 UTC, prisnir commented
retest this please

2018-06-29 14:46 UTC, prisnir commented
retest this please

2018-07-04 21:59 UTC, morgantaschuk requested changes

2018-07-04 21:59 UTC, morgantaschuk commented on decider-Estimate/CHANGELOG.md
> +## 2.6 - 2017-01-30
Is this changelog relevant? If not, remove.

2018-07-04 21:59 UTC, morgantaschuk commented on decider-Estimate/src/main/java/ca/on/oicr/pde/deciders/EstimateDecider.java
> +    private Map<String, BeSmall> fileSwaToSmall;
I thought we renamed the BeSmall class!!!!!

2018-07-04 21:59 UTC, morgantaschuk commented on decider-Estimate/src/main/java/ca/on/oicr/pde/deciders/EstimateDecider.java
> +                    rv.setExitStatus(ReturnValue.INVALIDARGUMENT);
This is an assumption that will break production someday. I suggest giving a warning but NOT exiting.

2018-07-04 21:59 UTC, morgantaschuk commented on decider-Estimate/src/main/java/ca/on/oicr/pde/deciders/EstimateDecider.java
> +        Log.debug("CHECK FILE DETAILS:" + fm);
This will produce a lot of cruft in the log file. Suggest removing it.

2018-07-04 21:59 UTC, morgantaschuk commented on decider-Estimate/src/main/java/ca/on/oicr/pde/deciders/EstimateDecider.java
> +        Log.debug("Number of files from file provenance = " + vals.size());
Remove this logging statement if it's not necessary.

2018-07-04 21:59 UTC, morgantaschuk commented on decider-Estimate/src/main/java/ca/on/oicr/pde/deciders/EstimateDecider.java
> +            Log.debug(r.getFiles().get(0).getFilePath());
Please remove extraneous debug statements.

2018-07-04 21:59 UTC, morgantaschuk commented on decider-Estimate/src/main/java/ca/on/oicr/pde/deciders/EstimateDecider.java
> +//        Map<String,Integer> rsemSTARMap = new HashMap<String,Integer>();
Remove this if not necessary

2018-07-04 21:59 UTC, morgantaschuk commented on decider-Estimate/src/main/java/ca/on/oicr/pde/deciders/EstimateDecider.java
> +    private class BeSmall {
😧

2018-07-04 21:59 UTC, morgantaschuk commented on workflow-Estimate/src/main/filters/workflow.properties
> +workflow-description=This workflow runs vasrcan2 tool to generate SNPS, Indels and copy number calls. It uses samtools,java and picard tools.
Change this

2018-07-04 21:59 UTC, morgantaschuk commented on workflow-Estimate/src/main/java/ca/on/oicr/pde/workflows/EstimateWorkflow.java
> +            ensFile = getWorkflowBaseDir() + "/dependencies/dahaner2017_liu2015_immune_genesets.gmt";
these should be set by INI file instead of hardcoding.

2018-07-04 21:59 UTC, morgantaschuk commented on workflow-Estimate/src/main/java/ca/on/oicr/pde/workflows/EstimateWorkflow.java
> +            estimateScript = getWorkflowBaseDir() + "/dependencies/estimate.R";
Set by INI file

2018-07-04 21:59 UTC, morgantaschuk commented on workflow-Estimate/src/main/java/ca/on/oicr/pde/workflows/EstimateWorkflow.java
> +        runEst.setMaxMemory(Integer.toString(this.estimateMem * 1024));
You already get this value up above at line 97, so you should use it from there.

2018-07-04 21:59 UTC, morgantaschuk commented on workflow-Estimate/src/main/java/ca/on/oicr/pde/workflows/EstimateWorkflow.java
> +        runEst.setQueue(getOptionalProperty("queue", ""));
You get queue above, line 95, you should use that value

2018-07-04 21:59 UTC, morgantaschuk commented on workflow-Estimate/src/main/java/ca/on/oicr/pde/workflows/EstimateWorkflow.java
> +        postProcessRSEMGeneCounts.setQueue(getOptionalProperty("queue", ""));
Same as above. Use memory and queue previously parsed.

2018-07-04 21:59 UTC, morgantaschuk commented on workflow-Estimate/src/main/java/ca/on/oicr/pde/workflows/EstimateWorkflow.java
> +        cmd.addArgument("if [ ! -z $STARG ]; then awk 'NR>3 {print $1}' $STARG | sed \"s/N\\_ambiguous/gene\\_id/\" > " + this.tmpDir + "sgene; fi;");
Hopefully this works. We occasionally have escaping problems when we pass strings in like this.

2018-07-04 21:59 UTC, morgantaschuk commented on workflow-Estimate/workflow/config/workflow.ini
> +star_inputs=#Output file configuration
It looks like your INI file got duplicated. Everything line 20 and below is the same as above.

2018-07-04 21:59 UTC, morgantaschuk commented on workflow-Estimate/workflow/config/workflow.ini
> +estimate_mem=20
I suggest naming this with "mem_mb" or "mem_gb" to make it clear the what units the memory is in.

2018-07-04 21:59 UTC, morgantaschuk commented on workflow-Estimate/workflow/dependencies/convert_rsem_results_zscore.r
> + gepData <- read.csv(gepFile, sep="\t", header=TRUE, check.names=FALSE)
Can you indent this file for easier reading?

2018-07-04 21:59 UTC, morgantaschuk commented on workflow-Estimate/workflow/dependencies/dahaner2017_liu2015_immune_genesets.gmt
> +Hematopoietic_stem_cell_CD133+_CD34dim	GSE24759_21_Liu2015	TRIP6	FSTL1	PFN2	SPINK2	FARP1	MLC1	PTPLA	HDGFRP3	ENO1	CD34	TFEC	ATP7B	MPDZ	SCN3A	STK32B	PPM1H	EPLIN	PLSCR4	WASF1	PLCXD1	HSPB1	DDEF2	SOCS2	IM
Did you really want to check this file in? Also the ensembl file in the same directory.

2018-07-10 20:40 UTC, prisnir commented
retest this please

2018-07-10 21:25 UTC, prisnir-zz commented
retest this please

2018-12-14 19:15 UTC, merged